image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: build
        services:
          - docker
        script:
          - docker run -v `pwd`/openid-4-verifiable-presentations:/data danielfett/markdown2rfc openid-4-verifiable-presentations-1_0.md
          - docker run -v `pwd`/openid-4-verifiable-credential-issuance:/data danielfett/markdown2rfc openid-4-verifiable-credential-issuance-1_0.md
          - docker run -v `pwd`/openid-connect-self-issued-v2:/data danielfett/markdown2rfc openid-connect-self-issued-v2-1_0.md
          - docker run -v `pwd`/openid-4-verifiable-presentations-over-ble:/data danielfett/markdown2rfc openid-4-verifiable-presentations-over-ble.md
          - mv openid-4-verifiable-presentations/openid-4-verifiable-presentations-*.html openid-4-verifiable-presentations-1_0.html
          - mv openid-4-verifiable-credential-issuance/openid-4-verifiable-credential-issuance-*.html openid-4-verifiable-credential-issuance-1_0.html
          - mv openid-connect-self-issued-v2/openid-connect-self-issued-v2-*.html openid-connect-self-issued-v2-1_0.html
          - mv openid-4-verifiable-presentations-over-ble/openid-for-verifiable-presentations-over-ble-*.html openid-4-verifiable-presentations-over-ble.html
        artifacts:
          - '*.html'
          - '*.xml'
  branches:
    master:
      - step:
          name: build
          services:
            - docker
          script:
            - docker run -v `pwd`/openid-4-verifiable-presentations:/data danielfett/markdown2rfc openid-4-verifiable-presentations-1_0.md
            - docker run -v `pwd`/openid-4-verifiable-credential-issuance:/data danielfett/markdown2rfc openid-4-verifiable-credential-issuance-1_0.md
            - docker run -v `pwd`/openid-connect-self-issued-v2:/data danielfett/markdown2rfc openid-connect-self-issued-v2-1_0.md
            - docker run -v `pwd`/openid-4-verifiable-presentations-over-ble:/data danielfett/markdown2rfc openid-4-verifiable-presentations-over-ble.md
            - mv openid-4-verifiable-presentations/openid-4-verifiable-presentations-*.html openid-4-verifiable-presentations-1_0.html
            - mv openid-4-verifiable-credential-issuance/openid-4-verifiable-credential-issuance-*.html openid-4-verifiable-credential-issuance-1_0.html
            - mv openid-connect-self-issued-v2/openid-connect-self-issued-v2-*.html openid-connect-self-issued-v2-1_0.html
            - mv openid-4-verifiable-presentations-over-ble/openid-for-verifiable-presentations-over-ble-*.html openid-4-verifiable-presentations-over-ble-1_0.html
          artifacts:
            - '*.html'
            - '*.xml'
      - step:
          name: publish
          clone:
            enabled: false
          script:
            - git config --global user.email "pipeline@bitbucket.org"
            - git config --global user.name "Bitbucket AB/Connect Pipeline"
            - git config --global push.default simple
            - git clone git@bitbucket.org:openid/openid.bitbucket.io.git
            - mkdir -p openid.bitbucket.io/connect/        
            - cp *.html openid.bitbucket.io/connect/
            - mkdir -p openid.bitbucket.io/connect/editors-draft   
            - cp *.html openid.bitbucket.io/connect/editors-draft
            - cd openid.bitbucket.io/connect
            - git add *
            - git commit -m "Update OID4VC drafts"
            - git push origin master