
@startuml img/uml.png

skinparam monochrome false
skinparam shadowing false

title SSI Wallet Attestation Process

participant tr as "Trust registry"
participant ce as "Attestation Service"
participant wa as "Wallet /\nHolder"
participant is as "Issuer"
participant ve as "Verifer /\nRelying Party"
participant us as "Holder"

== Issuance ==
is <->  us: user dialog
is -> wa: IIIR (credential offer - issuer) - deep link
wa -> is: get credential metadata (incl. security requirements, e.g. key_mechanisms, user authentication, attestation vc)
wa -> is: token request (pre-authz code): access_token
group on-demand attestation
    wa -> ce : token request (client credential, attestation VC): access token, c_nonce
    wa -> wa : perform wallet attestation\n(e.g. Play Integrity, iOS DeviceChecker, ...)
    wa -> wa : generate hardware-backed key (TEE, SE, ...)
    wa -> ce : credential issuance request (key, wallet attestation, proof & key attestation)
    ce -> ce : validate wallet attestation & key attestation
    ce -> wa : credential issuance response : wallet attestation VC
end
wa -> is : credential issuance request (wallet attestation VC VP, credential format, type)
is -> is : verify wallet attestation VC proof
is -> tr : request information on wallet certification
is -> wa : issue credential bound to wallet attestation VC
== Verification ==
ve <-> wa : presentation request (VC + WA VC)
wa -> ve : presentation of issuer's VCs (VC + WA VC)
ve <- ve : verify both VCs & check credential linkage
ve -> tr : request information on wallet certification
@enduml


Paul Bastian
Innovations
------------------------------------------------------------------
Bundesdruckerei GmbH 
Kommandantenstr. 18 
10969 Berlin

T + 49 (0) 30 – 2598 - 3385
F + 49 (0) 30 – 2598 - 2205 
paul.bastian@bdr.de
www.bundesdruckerei.de

Sitz der Gesellschaft: Berlin
Handelsregister: AG Berlin-Charlottenburg  HRB 80443. Ust.-IdNr.: DE 813210005
Aufsichtsratsvorsitzender: Willi Berchtold
Geschäftsführer: Dr.-Ing. Stefan Hofschen, Christian Helfrich
 
Die Unternehmen der Bundesdruckerei-Gruppe nehmen den Schutz Ihrer persönlichen Daten sehr ernst und beachten die einschlägigen Regeln der Datenschutzgrundverordnung und des Bundesdatenschutzgesetzes. Daher weisen wir darauf hin, dass im Rahmen unserer elektronisch geführten Kommunikation persönliche Daten erhoben und gegebenenfalls gespeichert werden. Diese Datenverarbeitung erfolgt ausschließlich zu geschäftlichen Zwecken. Sie haben das Recht, Auskunft über Ihre bei uns gespeicherten, persönlichen Daten zu beantragen. Bitte wenden Sie sich dazu an datenschutz-request@bdr.de. Weitere Hinweise zu Ihren Rechten und die Kontaktdaten unseres Datenschutzbeauftragten finden Sie unter: https://www.bundesdruckerei.de/de/Datenschutz.

Diese Mitteilung ist ausschließlich zur Kenntnisnahme durch die natürliche oder juristische Person bestimmt, an die sie adressiert ist. Sie kann vertrauliche Informationen enthalten, die nach geltendem Recht nicht weitergegeben werden dürfen. Sollten Sie nicht der beabsichtigte Empfänger der Mitteilung oder der Bevollmächtigte für die Weitergabe an den beabsichtigten Empfänger sein, teilen wir hiermit mit, dass jede Weitergabe, Weiterleitung oder Vervielfältigung dieser Mitteilung strengstens verboten ist. Wenn Sie diese Mitteilung irrtümlicherweise erhalten haben, löschen Sie sie bitte und teilen Sie uns dies umgehend mit.