
@startuml img/uml.png

skinparam monochrome false
skinparam shadowing false

title SSI Wallet Attestation Process

participant tr as "Trust registry"
participant ce as "Attestation Service"
participant wa as "Wallet /\nHolder"
participant is as "Issuer"
participant ve as "Verifer /\nRelying Party"
participant us as "Holder"

== Issuance ==
is <->  us: user dialog
is -> wa: IIIR (credential offer - issuer) - deep link
wa -> is: get credential metadata (incl. security requirements, e.g. key_mechanisms, user authentication, attestation vc)
wa -> is: token request (pre-authz code): access_token, c_nonce
group on-demand attestation
    wa -> ce : token request (client credential, attestation VC): access token, c_nonce
    wa -> wa : perform wallet attestation\n(e.g. Play Integrity, iOS DeviceChecker, ...)
    wa -> wa : generate hardware-backed key (TEE, SE, ...)
    wa -> ce : credential issuance request (key, wallet attestation, proof & key attestation)
    ce -> ce : validate wallet attestation & key attestation
    ce -> wa : credential issuance response : wallet attestation VC
end
wa -> wa: create wallet attestation VC VP (c_nonce)
wa -> is : credential issuance request (wallet attestation VC VP, credential format, type)
is -> is : verify wallet attestation VC proof
is -> tr : request information on wallet certification
is -> wa : issue credential bound to wallet attestation VC
== Verification ==
ve <-> wa : presentation request (VC + WA VC)
wa -> ve : presentation of issuer's VCs (VC + WA VC)
ve <- ve : verify both VCs & check credential linkage
ve -> tr : request information on wallet certification
@enduml