@startuml

title "Presentation: Same Device, Unknown Wallet provider, Large Response Payload"

participant "User Agent" as u

participant "Verifier" as r

participant "Verifier Backend" as rb

participant "Wallet" as w

u --> r : use
activate r
r --> u: presentation invite request\n(client_id, invite_uri, nonce)
deactivate r
u --> w: presentation invite request\n(client_id, invite_uri, nonce)
activate w
w -> rb: reply to invite (wallet_issuer, ephm enc key, ...)
rb -> w: presentation request (client_id, presentation_definition, ...) 
w -> w: authenticate and authorize Verifier

note over u, w: user authentication and credential selection/confirmation

w -> w: create verifiable presentation (credential)
w -> w: create response_code
w -> rb: post response (presentation response, hash(nonce,response_code))
w --> u: authorization response (response_code)
deactivate w
u --> r: authorization response (response_code)
activate r
r -> rb: get presentation response(response_code, nonce)
rb -> rb: lookup presentation response (hash(nonce,response_code))
note left: combination of response_code and nonce ensures binding of verifier and wallet transactions
rb -> r: presentation response
r -> r: validate presentation (incl. nonce binding)
r -> r: use presented credential 
@enduml