@startuml

autonumber

participant "User Agent" as u

participant "Verifier" as r

participant "Verifier Backend" as rb

participant "Wallet" as w

u --> r : use
activate r
r -> r: create transaction_id & state
r --> u: authorization request\n(client_id, nonce, response_uri, presentation_definition, state)
deactivate r
u --> w: authorization request\n(client_id, nonce, response_uri, presentation_definition, state)
activate w
w -> w: authenticate and\n authorize Verifier

note over u, w: user authentication and credential selection/confirmation

w -> w: create verifiable\npresentation (credential)
w -> rb: post response \n(vp_token, presentation_submission, state) : redirect_uri
w --> u: response (response_code)
deactivate w
u --> r: response (response_code)
activate r
r -> rb: get presentation response\n (transaction_id)
rb -> r: presentation response
r -> r: validate presentation \n(incl. nonce binding)
r -> r: use presented credential 
@enduml