@startuml

autonumber

title "Presentation: Same Device, Well-Known Wallet provider, Large Response Payload"

participant "User Agent" as u

participant "Verifier" as r

participant "Verifier Backend" as rb

participant "Wallet" as w

u --> r : use
r -> w: get metadata
activate r
w -> r: metadata
r -> r: create request_uri (client_id,\n nonce, redirect_uri, presentation_definition)
r --> u: authorization request\n(client_id, request_uri)
deactivate r
u --> w: authorization request\n(client_id, request_uri)
activate w
w -> rb: fetch request object 
w -> w: authenticate and authorize Verifier

note over u, w: user authentication and credential selection/confirmation

w -> w: create verifiable presentation (credential)
w -> w: create response_code
w -> rb: post response (presentation response, hash(nonce,response_code))
w --> u: authorization response (response_code)
deactivate w
u --> r: authorization response (response_code)
activate r
r -> rb: get presentation response(response_code, nonce)
rb -> rb: lookup presentation response (hash(nonce,response_code))
note left: combination of response_code and nonce ensures binding of verifier and wallet transactions
rb -> r: presentation response
r -> r: validate presentation (incl. nonce binding)
r -> r: use presented credential 
@enduml