@startuml

autonumber

title "Presentation: Cross Device, Well-known Wallet"

participant User as u

participant "Verifier" as r

participant "RP Backend" as rb

participant "Wallet Frontend" as w

participant "Wallet Provider Metadata" as b

u --> r : use
activate r

r --> r: create invite request\n(invite_uri, nonce)
deactivate r
r -> r: render QR code 

u --> w: scan QR code 
activate w
w -> rb: reply to invite (wallet_issuer, ephm enc key, ...)
rb -> b: get Wallet Metadata
rb -> w: presentation request (client_id, presentation_definition, ...) 

w -> w: authenticate and authorize Verifier

r -> rb : get presentation response (nonce)
rb -> r : no response yet

note over u, w: user authentication and credential selection/confirmation

w -> w: create presentation (credential)
w -> rb: presentation response \n(vp_token, presentation_submission, hash(nonce))
deactivate w
r -> rb: get presentation response (nonce)
rb -> r: presentation response \n(vp_token, presentation_submission)
r -> r: validate presentation
r -> r: use presented credential 
@enduml