@startuml

autonumber

participant User as u

participant "Verifier" as r

participant "Verfier Response Endpoint" as rb

participant "Wallet Frontend" as w

u --> r : use

r -> r: create transaction_id & state
r -> r: render QR code with signed presentation request

u --> w: scan QR code 
activate w
w -> w: authenticate and authorize Verifier

note over u, w: user authentication and credential selection/confirmation

w -> w: create presentation (credential)
w -> rb: presentation response \n(vp_token, presentation_submission, state)
deactivate w
r --> rb: get presentation response (transaction_id)
rb --> r: presentation response \n(vp_token, presentation_submission)
r -> r: validate presentation (including nonce)
r -> r: use presented credential 
@enduml